Explicitly require helper in test_case (#1297)
Currently, the helper is required through the Rake test task, which is
very implicit and means when running some tests directly some methods
are not available.

For example, running `bundle exec ruby -Itest
PATH_TO_RDOC/test/rdoc/test_rdoc_comment.rb` will trigger
`NoMethodError: undefined method 'assert_linear_performance' for an
instance of RDocCommentTest` because `test/lib/helper.rb` is not
required.

This commit makes the test case always require the helper and remove the
related options from the Rake test task.