Remove unused method RDoc::Require#top_level that always raises NoMethodError
It has been broken since 2d884240 (Move global parse state to RDoc::Store)
removed TopLevel.all_files_hash and TopLevel.all_files.

Result of `RDoc::Require.new('a','b').top_level` is basically unchanged.
Before: NoMethodError(undefined method 'all_files_hash')
After: NoMethodError(undefined method 'top_level')